-- Production 人工執行包：先完成 precheck；本檔不寫入 migration ledger。
begin;
-- Step 1：新增欄位。
alter table public.properties add column if not exists contract_signed_date date,add column if not exists sale_motivation text not null default '資金運用',add column if not exists sale_motivation_other text,add column if not exists current_condition_type text,add column if not exists current_condition_other text,add column if not exists current_usage text,add column if not exists current_usage_other text,add column if not exists building_style text,add column if not exists building_style_other text,add column if not exists parking_type text,add column if not exists parking_type_other text,add column if not exists road_width numeric,add column if not exists completion_date date,add column if not exists has_addition boolean not null default false,add column if not exists addition_description text,add column if not exists elementary_school_district text,add column if not exists junior_high_school_district text,add column if not exists showing_meeting_location text;
-- Step 2：移除舊 constraints/default，不刪資料。
alter table public.properties drop constraint if exists properties_sale_motivation_check,drop constraint if exists properties_current_condition_type_check,drop constraint if exists properties_current_usage_check,drop constraint if exists properties_building_style_check,drop constraint if exists properties_parking_type_check;
alter table public.properties alter column sale_motivation drop default;
-- Step 3：只在 udt_name=text 時轉型；已為 text[] 則跳過。
do $$declare t text;begin
 select udt_name into t from information_schema.columns where table_schema='public' and table_name='properties' and column_name='sale_motivation'; if t='text' then execute 'alter table public.properties alter column sale_motivation type text[] using (case when nullif(trim(sale_motivation),'''') is null then array[''資金運用'']::text[] else array[sale_motivation]::text[] end)'; elsif t<>'_text' then raise exception 'Unexpected sale_motivation type %',t; end if;
 select udt_name into t from information_schema.columns where table_schema='public' and table_name='properties' and column_name='current_condition_type'; if t='text' then execute 'alter table public.properties alter column current_condition_type type text[] using (case when nullif(trim(current_condition_type),'''') is null then ''{}''::text[] else array[current_condition_type]::text[] end)'; elsif t<>'_text' then raise exception 'Unexpected current_condition_type type %',t; end if;
 select udt_name into t from information_schema.columns where table_schema='public' and table_name='properties' and column_name='current_usage'; if t='text' then execute 'alter table public.properties alter column current_usage type text[] using (case when nullif(trim(current_usage),'''') is null then ''{}''::text[] else array[current_usage]::text[] end)'; elsif t<>'_text' then raise exception 'Unexpected current_usage type %',t; end if;
 select udt_name into t from information_schema.columns where table_schema='public' and table_name='properties' and column_name='building_style'; if t='text' then execute 'alter table public.properties alter column building_style type text[] using (case when nullif(trim(building_style),'''') is null then ''{}''::text[] else array[building_style]::text[] end)'; elsif t<>'_text' then raise exception 'Unexpected building_style type %',t; end if;
 select udt_name into t from information_schema.columns where table_schema='public' and table_name='properties' and column_name='parking_type'; if t='text' then execute 'alter table public.properties alter column parking_type type text[] using (case when nullif(trim(parking_type),'''') is null then ''{}''::text[] else array[parking_type]::text[] end)'; elsif t<>'_text' then raise exception 'Unexpected parking_type type %',t; end if;
end$$;
-- Step 4：array default。
alter table public.properties alter column sale_motivation set default array['資金運用']::text[];
-- Step 5：constraints。
do $$begin
 if not exists(select 1 from pg_constraint where conname='properties_sale_motivation_check') then alter table public.properties add constraint properties_sale_motivation_check check(sale_motivation <@ array['換屋','工作','就學','家庭組成改變','移民','資金運用','其他']::text[]);end if;
 if not exists(select 1 from pg_constraint where conname='properties_current_condition_type_check') then alter table public.properties add constraint properties_current_condition_type_check check(current_condition_type <@ array['空屋','自用','出租','結構體','其他']::text[]);end if;
 if not exists(select 1 from pg_constraint where conname='properties_current_usage_check') then alter table public.properties add constraint properties_current_usage_check check(current_usage <@ array['住宅','店面','辦公','住辦','住店','廠房','倉庫','土地','車位','其他']::text[]);end if;
 if not exists(select 1 from pg_constraint where conname='properties_building_style_check') then alter table public.properties add constraint properties_building_style_check check(building_style <@ array['透天','別墅','農舍','公寓','華廈','電梯大樓','套房','店面','廠房','倉庫','土地','其他']::text[]);end if;
 if not exists(select 1 from pg_constraint where conname='properties_parking_type_check') then alter table public.properties add constraint properties_parking_type_check check(parking_type <@ array['無','車庫','門前停車','騎樓停車','庭院停車','平面車位','機械車位','露天停車','其他']::text[]);end if; end$$;
-- Step 6：indexes。
create index if not exists properties_contract_signed_date_idx on public.properties(contract_signed_date); create index if not exists properties_completion_date_idx on public.properties(completion_date);
-- Step 7：不 INSERT supabase_migrations.schema_migrations；請用官方受控流程另行 reconciliation。
-- Step 8：基本驗證。
do $$begin if (select count(*) from information_schema.columns where table_schema='public' and table_name='properties' and column_name in ('contract_signed_date','sale_motivation','sale_motivation_other','current_condition_type','current_condition_other','current_usage','current_usage_other','building_style','building_style_other','parking_type','parking_type_other','road_width','completion_date','has_addition','addition_description','elementary_school_district','junior_high_school_district','showing_meeting_location'))<>18 then raise exception 'Expected 18 business columns';end if;end$$;
commit;
