"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRole } from "@/lib/auth";
import { relationInputSchema } from "@/lib/people-properties";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export async function createPropertyPeopleAction(formData: FormData) { await requireRole(["editor","admin","owner"]); const propertyId=String(formData.get("property_id")||""); const parsed=relationInputSchema.safeParse(Object.fromEntries(formData.entries())); if(!parsed.success) redirect(`/admin/properties/${propertyId}/edit?relation_error=invalid`); const supabase=await createSupabaseServerClient(); const {error}=await supabase.from("people_properties").insert({...parsed.data,relationship_label:parsed.data.relationship_label||null,note:parsed.data.note||null,started_at:parsed.data.started_at||null}); if(error) redirect(`/admin/properties/${propertyId}/edit?relation_error=${error.code==="23505"?"duplicate":"save"}`); revalidatePath(`/admin/properties/${propertyId}/edit`); revalidatePath(`/admin/people/${parsed.data.person_id}`); redirect(`/admin/properties/${propertyId}/edit?relation_saved=1`); }
export async function updatePropertyPeopleAction(formData: FormData) { await requireRole(["editor","admin","owner"]); const propertyId=String(formData.get("property_id")||""); const relationId=String(formData.get("id")||""); const parsed=relationInputSchema.safeParse(Object.fromEntries(formData.entries())); if(!parsed.success) redirect(`/admin/properties/${propertyId}/edit?relation_error=invalid`); const supabase=await createSupabaseServerClient(); const {error}=await supabase.from("people_properties").update({relationship_type:parsed.data.relationship_type,relationship_label:parsed.data.relationship_label||null,note:parsed.data.note||null,started_at:parsed.data.started_at||null,ended_at:parsed.data.ended_at||null}).eq("id",relationId).eq("property_id",propertyId).eq("person_id",parsed.data.person_id).eq("status","active"); if(error) redirect(`/admin/properties/${propertyId}/edit?relation_error=${error.code==="23505"?"duplicate":"save"}`); revalidatePath(`/admin/properties/${propertyId}/edit`); revalidatePath(`/admin/people/${parsed.data.person_id}`); redirect(`/admin/properties/${propertyId}/edit?relation_saved=1`); }
export async function archivePropertyPeopleAction(id:string,propertyId:string,personId:string) { await requireRole(["editor","admin","owner"]); const supabase=await createSupabaseServerClient(); const {error}=await supabase.from("people_properties").update({status:"archived",archived_at:new Date().toISOString(),ended_at:new Date().toISOString()}).eq("id",id); if(error) redirect(`/admin/properties/${propertyId}/edit?relation_error=archive`); revalidatePath(`/admin/properties/${propertyId}/edit`); revalidatePath(`/admin/people/${personId}`); redirect(`/admin/properties/${propertyId}/edit?relation_saved=archived`); }
