"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { activityLabels, activityTypes } from "@/lib/people-properties";
import { formatTaipeiRelationDate } from "@/lib/format";
import { PeoplePropertyRelationForm } from "@/components/admin/people-property-relation-form";
type Props = { personId: string; properties: Array<{ id: string; title: string }>; activities: Array<{ id: string; activity_type: keyof typeof activityLabels; activity_date: string; note: string | null; created_at: string }> };
export function PeopleRelationshipCapture({ personId, properties, activities }: Props) {
  const router = useRouter(); const [mode, setMode] = useState<"activity" | "property">("activity"); const [type, setType] = useState("visit"); const [date, setDate] = useState(() => new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Taipei" })); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); setMessage(""); const res = await fetch("/api/admin/people-activities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ person_id: personId, activity_type: type, activity_date: date, note }) }); const body = await res.json().catch(() => null); setBusy(false); if (!res.ok || !body?.ok) { setError(body?.message || "拜訪紀錄儲存失敗。"); return; } setMessage(body.message); setNote(""); router.refresh(); }
  return <section className="card" style={{ marginTop: 18 }}><div className="card-body"><h2 style={{ marginTop: 0 }}>新增客戶關係紀錄</h2><label className="field"><span>紀錄類型</span><select className="select" value={mode} onChange={(e) => setMode(e.target.value as "activity" | "property")}><option value="activity">拜訪客戶／尚無特定物件</option><option value="property">關聯既有物件</option></select></label>{mode === "activity" ? <form className="form-grid" onSubmit={submit}><label className="field"><span>紀錄日期</span><input className="input" type="date" value={date} onChange={(e) => setDate(e.target.value)} required /></label><label className="field"><span>紀錄方式</span><select className="select" value={type} onChange={(e) => setType(e.target.value)}>{activityTypes.map((t) => <option key={t} value={t}>{activityLabels[t]}</option>)}</select></label><label className="field full"><span>備註</span><textarea className="textarea" value={note} onChange={(e) => setNote(e.target.value)} maxLength={2000} /></label>{error ? <div className="notice" role="alert">{error}</div> : null}{message ? <div className="notice" role="status">{message}</div> : null}<button className="button" type="submit" disabled={busy}>{busy ? "儲存中…" : "建立拜訪紀錄"}</button></form> : <PeoplePropertyRelationForm mode="create" personId={personId} propertyId="" propertyOptions={properties} />}
  <h3>客戶活動紀錄</h3>{activities.length ? <div className="table-wrap"><table><thead><tr><th>日期</th><th>方式</th><th>備註</th><th>建立時間</th></tr></thead><tbody>{activities.map((activity) => <tr key={activity.id}><td>{formatTaipeiRelationDate(activity.activity_date)}</td><td>{activityLabels[activity.activity_type] || activity.activity_type}</td><td>{activity.note || "-"}</td><td>{formatTaipeiRelationDate(activity.created_at)}</td></tr>)}</tbody></table></div> : <p className="muted">尚無客戶活動紀錄</p>}</div></section>;
}
