import assert from "node:assert/strict";
import { chatSchema, inferNeeds, needsFilters, needsSchema, needsSummary, redactContact } from "../lib/concierge/schema.ts";
import { signReply, verifyReply } from "../lib/concierge/audio-token.ts";
import { takeConciergeSlot } from "../lib/concierge/limit.ts";
const empty = needsSchema.parse({});
const first = inferNeeds("鹿港或福興，800萬以下住宅，需要孝親房", empty);
assert.deepEqual(first.districts, ["鹿港鎮", "福興鄉"]);
assert.equal(first.maxPrice, 800);
assert.equal(first.type, "residential");
assert.equal(first.mustHave, "孝親房");
const second = inferNeeds("要電梯和車位", first);
assert.equal(second.maxPrice, 800);
assert.deepEqual(second.districts, first.districts);
assert.equal(second.mustHave, "孝親房、電梯、車位");
assert.equal(inferNeeds("我想委託出售秀水透天", first).intent, "sell");
assert.equal(inferNeeds("我想委託出售秀水透天", first).maxPrice, null);
assert.equal(inferNeeds("我想找鹿港住宅", { ...empty, intent: "question" }).intent, "buy");
assert.equal(inferNeeds("想租屋", empty).intent, "rent");
assert.equal(inferNeeds("委託出租", empty).intent, "let");
assert.equal(inferNeeds("貸款怎麼辦", empty).intent, "question");
assert.equal(inferNeeds("500到1000萬農地", empty).minPrice, 500);
assert.equal(needsFilters(first).maxPrice, 800);
assert.match(needsSummary(first), /孝親房/);
assert.equal(chatSchema.safeParse({ message: "x".repeat(501) }).success, false);
assert.equal(needsSchema.safeParse({ districts: ["不存在地區"] }).success, false);
assert.equal(needsSchema.safeParse({ type: "private_owner" }).success, false);
assert.equal(needsSchema.safeParse({ minPrice: 1000, maxPrice: 500 }).success, false);
assert.ok(!redactContact("電話0938137177，foo@example.com").includes("0938137177"));
assert.ok(!redactContact("foo@example.com").includes("foo@example.com"));
const now = Date.now();
const token = await signReply({ text: "阿美陪你找房", role: "amei", expires: now + 60000 }, "test-only-secret");
assert.equal((await verifyReply(token, "test-only-secret", now))?.role, "amei");
assert.equal(await verifyReply(token, "wrong-secret", now), null);
assert.equal(await verifyReply(token, "test-only-secret", now + 60001), null);
assert.equal(await verifyReply(token.replace(/^./, "x"), "test-only-secret", now), null);
assert.equal(await verifyReply(await signReply({ text: "x".repeat(1201), role: "ayong", expires: now + 1000 }, "key"), "key", now), null);
const slots = Array.from({ length: 4 }, () => takeConciergeSlot("test", now));
assert.equal(takeConciergeSlot("test", now), null);
slots.forEach(release => release?.());
assert.ok(takeConciergeSlot("test", now));
console.log("PASS concierge requirements, public filters, validation, redaction, signed audio, concurrency guard");
