import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { relationInputSchema, relationshipTypes } from "../lib/people-properties.ts";
import { dateInputToTaipeiIso, formatTaipeiRelationDate, toTaipeiDateInput } from "../lib/format.ts";

const ids = { person_id: "00000000-0000-0000-0000-000000000001", property_id: "00000000-0000-0000-0000-000000000002" };
const valid = { ...ids, relationship_type: "buyer", relationship_label: "", note: "看屋", started_at: "2026-01-01", ended_at: "" };
assert.equal(relationInputSchema.safeParse(valid).success, true);
assert.equal(relationInputSchema.safeParse({ ...valid, relationship_type: "invalid" }).success, false);
assert.equal(relationInputSchema.safeParse({ ...valid, relationship_type: "other", relationship_label: "" }).success, false);
assert.equal(relationInputSchema.safeParse({ ...valid, started_at: "2026-02-01", ended_at: "2026-01-01" }).success, false);
assert.equal(relationInputSchema.safeParse({ ...valid, person_id: "not-a-uuid" }).success, false);
assert.deepEqual(relationshipTypes, ["owner", "buyer", "viewer", "negotiator", "tenant", "landlord", "referrer", "contact", "other"]);
const route = readFileSync("app/api/admin/people-properties/route.ts", "utf8");
const detailRoute = readFileSync("app/api/admin/people-properties/[id]/route.ts", "utf8");
const archiveRoute = readFileSync("app/api/admin/people-properties/[id]/archive/route.ts", "utf8");
assert.match(route, /export async function POST/);
assert.match(detailRoute, /export async function PATCH/);
assert.match(archiveRoute, /export async function POST/);
assert.match(route, /RELATION_DUPLICATE/);
assert.match(detailRoute, /RELATION_FORBIDDEN/);
assert.match(archiveRoute, /status: "archived"/);
assert.equal(dateInputToTaipeiIso("2026-07-30"), "2026-07-30T00:00:00+08:00");
assert.equal(toTaipeiDateInput("2026-07-29T16:00:00.000Z"), "2026-07-30");
assert.equal(toTaipeiDateInput("2026-07-30T00:00:00+08:00"), "2026-07-30");
assert.equal(formatTaipeiRelationDate("2026-07-29T16:00:00.000Z"), "115/07/30");
assert.equal(formatTaipeiRelationDate(null), "-");
assert.equal(dateInputToTaipeiIso("2026-02-30"), null);
const activityRoute = readFileSync("app/api/admin/people-activities/route.ts", "utf8");
assert.match(activityRoute, /export const runtime = "edge"/);
assert.match(activityRoute, /ACTIVITY_FORBIDDEN/);
assert.match(activityRoute, /ACTIVITY_SCHEMA_MISSING/);
assert.match(activityRoute, /status: 201/);
console.log("people-property relation validation: PASS");
