import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { requirementInputSchema } from "../lib/customer-requirements/schema.ts";
import { buildRequirementPayload, tenThousandsToTwd, twdToTenThousands } from "../lib/customer-requirements/payload.ts";
import { getRequirementCompleteness } from "../lib/customer-requirements/completeness.ts";
import { allowedPropertyCategories, normalizePropertyCategories, propertyCategoryLabel, requirementTypeLabel, statusTransitions } from "../lib/customer-requirements/constants.ts";

const base = { person_id:"11111111-1111-4111-8111-111111111111", title:" 和美孝親三房 ", requirement_type:"residential", transaction_type:"buy", status:"active", urgency:"high", property_categories:["townhouse"], cities:["彰化縣"], districts:["和美鎮"], area_note:"", sale_budget_min:500, sale_budget_max:800, rent_budget_min:null, rent_budget_max:null, must_have:["電梯"], nice_to_have:[], unacceptable:[] };
const parsed = requirementInputSchema.parse(base);
assert.equal(parsed.title, "和美孝親三房");
assert.equal(tenThousandsToTwd(800), 8_000_000);
assert.equal(twdToTenThousands(8_000_000), 800);
const payload = buildRequirementPayload(parsed);
assert.equal(payload.sale_budget_max, 8_000_000);
assert.equal(payload.nice_to_have, null);
assert.equal(payload.area_note, null);
assert.equal(requirementInputSchema.safeParse({ ...base, property_categories:[] }).success, false);
assert.equal(requirementInputSchema.safeParse({ ...base, cities:[], districts:[], area_note:"" }).success, false);
assert.equal(requirementInputSchema.safeParse({ ...base, sale_budget_min:900, sale_budget_max:800 }).success, false);
assert.equal(requirementInputSchema.safeParse({ ...base, sale_budget_max:-1 }).success, false);
assert.equal(requirementInputSchema.safeParse({ ...base, transaction_type:"rent", sale_budget_min:null, sale_budget_max:null, rent_budget_max:20 }).success, true);
assert.equal(requirementInputSchema.safeParse({ ...base, transaction_type:"rent", rent_budget_max:20 }).success, false);
assert.deepEqual(statusTransitions.active, ["paused","fulfilled","archived"]);
assert.deepEqual(statusTransitions.archived, []);
assert.deepEqual(allowedPropertyCategories("residential"),["townhouse","apartment","building","other"]);
assert.equal(allowedPropertyCategories("residential").includes("factory"),false);
assert.equal(allowedPropertyCategories("residential").includes("warehouse"),false);
assert.equal(allowedPropertyCategories("residential").includes("farmland"),false);
assert.deepEqual(allowedPropertyCategories("factory"),["factory","warehouse"]);
assert.deepEqual(allowedPropertyCategories("building_land"),["building_land","land"]);
assert.deepEqual(normalizePropertyCategories("factory",["townhouse","factory","warehouse"]),["factory","warehouse"]);
assert.equal(requirementInputSchema.safeParse({...base,requirement_type:"residential",property_categories:["factory"]}).success,false);
assert.equal(requirementTypeLabel("legacy_type"),"未知需求類型");
assert.equal(propertyCategoryLabel("legacy_category"),"未知物件類型");
assert.equal(propertyCategoryLabel("townhouse"),"透天厝");
assert.equal(propertyCategoryLabel("apartment"),"公寓");
assert.equal(propertyCategoryLabel("building"),"電梯大樓");
const completeness=getRequirementCompleteness(parsed as unknown as Record<string,unknown>);
assert.equal(completeness.sections.find(x=>x.label==="客需資料")?.complete,true);

const migration=readFileSync("supabase/migrations/202608020201_crm_customer_requirements_phase_1.sql","utf8");
assert.match(migration,/can_access_person\(person_id\)/);
assert.match(migration,/using gin\(property_categories\)/);
assert.match(migration,/requirement_duplicated/);
assert.match(migration,/revoke all on public\.crm_customer_requirements from anon/);
const form=readFileSync("components/admin/customer-requirement-form.tsx","utf8");
assert.match(form,/client fetch JSON|fetch\(/);
assert.match(form,/if\(busy\)return/);
assert.match(form,/fieldErrors/);
assert.match(form,/firstError/);
const list=readFileSync("lib/customer-requirements/queries.ts","utf8");
assert.match(list,/\.range\(from,to\)/);
assert.doesNotMatch(list,/assignee:profiles!crm_customer_requirements_assigned_user_id_fkey/);
assert.match(list,/person:people\(id,display_name\)/);
console.log("CRM Customer Requirements Phase 1 tests: PASS");
