import assert from 'node:assert/strict';
import {parsePastedProperty} from '../lib/properties/ai-parser.ts';
import {parsePropertySearch} from '../lib/properties/search.ts';
import {propertySchema, toPropertyPayload} from '../lib/properties/schema.ts';
import {formatPropertyPrice} from '../lib/format.ts';
const rental = parsePastedProperty(`新接租件\n租金：128,000元/月\n押金：兩個月\n最短租期：三年\n原餐飲設備，包含蒸煮油炸設備、兩部冷凍櫃，擁有HACCP先期輔導證明標章\nPS.租約須經公證`);
assert.equal(rental.transaction_type,'rent');
assert.equal(rental.rent_monthly,'128000');
assert.equal(rental.deposit_months,'2');
assert.equal(rental.minimum_lease_months,'36');
assert.equal(rental.lease_notarization_required,'true');
assert.equal(rental.price,'');
assert.match(rental.rental_equipment || '', /兩部冷凍櫃/);
assert.doesNotMatch(rental.rental_equipment || '', /HACCP/);
assert.equal(formatPropertyPrice({transaction_type:'rent',rent_monthly:128000}), '128,000 元／月');
assert.equal(parsePropertySearch('出租3房').price, null);
assert.equal(parsePropertySearch('出租15萬元以下').price,150000);
console.log('Rental parsing, units and sales isolation PASS');

const base = {title:'測試物件',slug:'rental-validation',property_type:'factory',status:'published'};
assert.equal(propertySchema.safeParse({...base,transaction_type:'rent'}).success,false);
assert.equal(propertySchema.safeParse({...base,transaction_type:'rent',rent_monthly:0}).success,false);
assert.equal(propertySchema.safeParse({...base,transaction_type:'rent',rent_monthly:128000,deposit_months:-1}).success,false);
const validRent = propertySchema.parse({...base,transaction_type:'rent',price:1280,rent_monthly:128000,deposit_months:2,minimum_lease_months:36,lease_notarization_required:true});
assert.equal(toPropertyPayload(validRent).price,null);
assert.equal(toPropertyPayload(validRent).rent_monthly,128000);
const validSale = propertySchema.parse({...base,transaction_type:'sale',price:1280,rent_monthly:128000,lease_notarization_required:true});
assert.equal(toPropertyPayload(validSale).rent_monthly,null);
assert.equal(toPropertyPayload(validSale).price,1280);
assert.equal(toPropertyPayload(validSale).lease_notarization_required,false);
console.log('Rental validation, zero/negative rejection and transaction-switch payload PASS');
