import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const migration = readFileSync("supabase/migrations/202608130101_area_pages_and_property_availability.sql", "utf8");
const detail = readFileSync("app/(public)/properties/[slug]/page.tsx", "utf8");
const actions = readFileSync("app/admin/properties/actions.ts", "utf8");
const adminAreas = readFileSync("app/admin/areas/page.tsx", "utf8");
const areaForm = readFileSync("components/admin/area-page-form.tsx", "utf8");
assert.match(migration, /create table if not exists public\.area_pages/);
assert.match(migration, /public read published area pages/);
assert.match(migration, /get_public_property_availability/);
assert.match(migration, /security definer/);
assert.match(migration, /add column if not exists city/);
assert.match(migration, /add column if not exists unavailable_reason/);
assert.match(detail, /此物件已下架/);
assert.match(detail, /robots: \{ index: false/);
assert.doesNotMatch(detail, /availabilityResult[\s\S]{0,120}property\.title/);
assert.match(actions, /unavailable_reason: reason/);
assert.match(actions, /unavailable_reason: null/);
assert.match(adminAreas, /新增服務地區/);
assert.match(areaForm, /FAQ（每行：問題｜回答）/);
console.log("area CMS and property availability regression checks passed");
