import { NextResponse } from "next/server";
import { requireApiRole } from "@/lib/auth-api";
import { recordAuditLog } from "@/lib/audit/audit-log";
import { insertRequirementActivity } from "@/lib/customer-requirements/activity";
import { buildRequirementPayload } from "@/lib/customer-requirements/payload";
import { dbErrorStatus, listRequirements } from "@/lib/customer-requirements/queries";
import { fieldErrors, requirementInputSchema, requirementListQuerySchema } from "@/lib/customer-requirements/schema";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export const runtime="edge";
const fail=(status:number,code:string,message:string,fields?:Record<string,string>)=>NextResponse.json({ok:false,code,message,fieldErrors:fields},{status});
export async function GET(request:Request){const auth=await requireApiRole(["editor","admin","owner"]);if(auth.response)return auth.response;const u=new URL(request.url);const parsed=requirementListQuerySchema.safeParse(Object.fromEntries(u.searchParams));if(!parsed.success)return fail(400,"INVALID_QUERY","查詢條件格式錯誤");const supabase=await createSupabaseServerClient();const {data,error,count}=await listRequirements(supabase,parsed.data);if(error)return fail(dbErrorStatus(error.code),"REQUIREMENTS_LOAD_FAILED","客需資料讀取失敗");return NextResponse.json({items:data||[],page:parsed.data.page,pageSize:parsed.data.pageSize,total:count||0,totalPages:Math.max(1,Math.ceil((count||0)/parsed.data.pageSize))});}
export async function POST(request:Request){const auth=await requireApiRole(["editor","admin","owner"]);if(auth.response)return auth.response;let body:unknown;try{body=await request.json();}catch{return fail(400,"INVALID_JSON","請提供有效 JSON");}const parsed=requirementInputSchema.safeParse(body);if(!parsed.success)return fail(422,"VALIDATION_FAILED","請修正客需欄位",fieldErrors(parsed.error));const supabase=await createSupabaseServerClient();const {data:person,error:pe}=await supabase.from("people").select("id").eq("id",parsed.data.person_id).maybeSingle();if(pe)return fail(dbErrorStatus(pe.code),"PERSON_LOOKUP_FAILED","客戶資料查詢失敗");if(!person)return fail(404,"PERSON_NOT_FOUND","找不到指定客戶");const payload={...buildRequirementPayload(parsed.data),status:"active",created_by:auth.current!.user.id,updated_by:auth.current!.user.id};const {data,error}=await supabase.from("crm_customer_requirements").insert(payload).select().single();if(error)return fail(dbErrorStatus(error.code),"REQUIREMENT_CREATE_FAILED","客需建立失敗");const activity=await insertRequirementActivity(supabase,{personId:data.person_id,requirementId:data.id,type:"requirement_created",title:data.title,userId:auth.current!.user.id});if(activity.error){await supabase.from("crm_customer_requirements").delete().eq("id",data.id);return fail(500,"ACTIVITY_CREATE_FAILED","客需活動紀錄建立失敗，已取消本次新增");}await recordAuditLog({action:"requirement_created",resourceType:"crm_customer_requirement",resourceId:data.id,afterData:{id:data.id,title:data.title,status:data.status},userId:auth.current!.user.id,userEmail:auth.current!.user.email,actorRole:auth.current!.profile.role});return NextResponse.json({ok:true,item:data},{status:201});}
